title: Operation Seamless
description: A Recovered Archive, 1888â€“1901
baseurl: "" # Leave empty for your main domain
url: "https://andreas-breidenthal.github.io"

# This tells Jekyll to process your documents as a collection
collections:
  documents:
    output: true
    permalink: /archive/:path/

# Markdown settings
kramdown:
  input: GFM # GitHub Flavored Markdown
